### ISSUE TITLE
`pod install` error

### ISSUE THREAD

**Issue by afeiship** [CYXiang/CYXTenMinDemo#1]
## Command
- cd .../CYXTenMinDemo/TenMinDemo
- `pod install` 
## Error infos:

Re-creating CocoaPods due to major version update.
Analyzing dependencies
[!] The dependency `AFNetworking` is not used in any concrete target.
The dependency `SDWebImage` is not used in any concrete target.
The dependency `MJExtension` is not used in any concrete target.
The dependency `MJRefresh` is not used in any concrete target.
The dependency `SVProgressHUD` is not used in any concrete target.

**Comment by CYXiang** [comment]
你的cocoa pods版本是1.0.0以上的，pod file格式要加上
`
target 'YourApp' do
  pod 'AFNetworking', '~> 2.6'
...
end 
`
或者你回退到0.39.0版本的cocoapods
